### ISSUE TITLE
How to create endpoint with parameters in url?

### ISSUE THREAD

**Issue by sulmar** [mocktastic/mocktastic#3]
I would like to create endpoint:
> https://nominatim.openstreetmap.org/search?q=10+dworzec+zachodni,+warszawa&format=json

How I can mock this real-world url?

**Comment by mocktastic** [comment]
Apologies for the late response. 

To mock this endoint:
1. Create a mock server with any name and port number.
2. Create an endpoint with the path and method. In this case the path is `/search`, and the method is 'GET'.
3. Create a new response for this endpoint, with the `Content-Type` header as `application/json`, and body as

```json
[
  {
    "boundingbox": [
      "52.2150627",
      "52.2250627",
      "20.9602859",
      "20.9702859"
    ],
    "class": "railway",
    "display_name": "Warszawa Zachodnia, Tunelowa, Czyste, Wola, Warsaw, Warszawa, Masovian Voivodeship, 01-221, Poland",
    "icon": "https://nominatim.openstreetmap.org/images/mapicons/transport_train_station2.p.20.png",
    "importance": 0.610973687119958,
    "lat": "52.2200627",
    "licence": "Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright",
    "lon": "20.9652859",
    "osm_id": "3390821831",
    "osm_type": "node",
    "place_id": "45646475",
    "type": "station"
  }
]
```
4. Now run the server, and you should be able to hit the `/search` endpoint on your localhost.

For detailed instructions on how to create servers, endpoints or responses, and how to run your mock server, [check out our docs](https://docs.mocktastic.com/#/md/getting-started/create-rest-api).

If you need dynamic responses for this endpoint, please refer our ['Response Templating' docs](https://docs.mocktastic.com/#/md/templating/basics).
